"""empty message

Revision ID: 5bf9d0e74874
Revises: 70dec1fdd7a1
Create Date: 2020-05-21 20:45:47.626312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bf9d0e74874'
down_revision = '70dec1fdd7a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_leave_date_req', table_name='leave')
    op.drop_index('ix_leave_days_av', table_name='leave')
    op.drop_index('ix_leave_timestamp', table_name='leave')
    op.drop_table('leave')
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_sect', table_name='user')
    op.drop_column('user', 'sect')
    op.drop_column('user', 'email')
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=120), nullable=True))
    op.add_column('user', sa.Column('sect', sa.VARCHAR(length=10), nullable=True))
    op.create_index('ix_user_sect', 'user', ['sect'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=1)
    op.create_table('leave',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('days_av', sa.INTEGER(), nullable=True),
    sa.Column('days_req', sa.INTEGER(), nullable=True),
    sa.Column('date_req', sa.VARCHAR(length=10), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_leave_timestamp', 'leave', ['timestamp'], unique=False)
    op.create_index('ix_leave_days_av', 'leave', ['days_av'], unique=False)
    op.create_index('ix_leave_date_req', 'leave', ['date_req'], unique=1)
    # ### end Alembic commands ###
