"""Leave table

Revision ID: 70dec1fdd7a1
Revises: e50cb0527abc
Create Date: 2019-05-25 20:50:49.350923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70dec1fdd7a1'
down_revision = 'e50cb0527abc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('days_av', sa.Integer(), nullable=True),
    sa.Column('days_req', sa.Integer(), nullable=True),
    sa.Column('date_req', sa.String(length=10), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_date_req'), 'leave', ['date_req'], unique=True)
    op.create_index(op.f('ix_leave_days_av'), 'leave', ['days_av'], unique=False)
    op.create_index(op.f('ix_leave_timestamp'), 'leave', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leave_timestamp'), table_name='leave')
    op.drop_index(op.f('ix_leave_days_av'), table_name='leave')
    op.drop_index(op.f('ix_leave_date_req'), table_name='leave')
    op.drop_table('leave')
    # ### end Alembic commands ###
